import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBars,
  faHouse,
  faPenToSquare,
  faPen,
} from "@fortawesome/free-solid-svg-icons";
import LoginBtn from "./board/component/LoginBtn";
import LogoutBtn from "./board/component/LogoutBtn";
import { getServerSession } from "next-auth";
import SignUp from "./board/component/signupBtn";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-header">
          <FontAwesomeIcon icon={faBars} className="menu-icon" />
          <span className="title">게시판 프로젝트</span>
          <div className="login">
            {session ? (
              <span>
                {session.user.name} <LogoutBtn />
              </span>
            ) : (
              <span>
                <LoginBtn />
                <SignUp />
              </span>
            )}
          </div>
        </div>
        <div className="main-body">
          <div className="main-navbar">
            <Link href="/">
              <FontAwesomeIcon icon={faHouse} className="navbar-icon" />
              <span>Home</span>
            </Link>
            <Link href="/board">
              <FontAwesomeIcon icon={faPenToSquare} className="navbar-icon" />
              <span>Board</span>
            </Link>
            <Link href="/board/write">
              <FontAwesomeIcon icon={faPen} className="navbar-icon" />
              <span>Write(임시)</span>
            </Link>
          </div>
          <div className="main-page">{children}</div>
        </div>
      </body>
    </html>
  );
}
